// FurInventory Pro - Sector Templates
// Pre-built field configurations for different industry sectors
import { CustomField } from '../types';

export interface SectorTemplate {
    id: string;
    name: string;
    emoji: string;
    description: string;
    color: string;
    fields: Omit<CustomField, 'id' | 'order' | 'isSystem'>[];
}

export const SECTOR_TEMPLATES: SectorTemplate[] = [
    {
        id: 'pellicce',
        name: 'Pellicce & Pellicceria',
        emoji: '🧥',
        description: 'Gestione pellicce: taglia, colore, stagione, fornitore, certificazione',
        color: '#8B4513',
        fields: [
            { name: 'Taglia', type: 'single_choice', uiType: 'segmented', icon: 'straighten', required: false, options: [{ id: 'xs', label: 'XS' }, { id: 's', label: 'S' }, { id: 'm', label: 'M' }, { id: 'l', label: 'L' }, { id: 'xl', label: 'XL' }, { id: 'xxl', label: 'XXL' }], dataset: ['XS', 'S', 'M', 'L', 'XL', 'XXL'] },
            { name: 'Colore', type: 'single_choice', uiType: 'grid', icon: 'palette', required: false, options: [{ id: 'nero', label: 'Nero' }, { id: 'marrone', label: 'Marrone' }, { id: 'bianco', label: 'Bianco' }, { id: 'grigio', label: 'Grigio' }, { id: 'beige', label: 'Beige' }, { id: 'rosso', label: 'Rosso' }], dataset: ['Nero', 'Marrone', 'Bianco', 'Grigio', 'Beige', 'Rosso'] },
            { name: 'Stagione', type: 'single_choice', uiType: 'segmented', icon: 'ac-unit', required: false, options: [{ id: 'ai', label: 'A/I' }, { id: 'pe', label: 'P/E' }, { id: 'trans', label: 'Transizione' }], dataset: ['A/I', 'P/E', 'Transizione'] },
            { name: 'Fornitore', type: 'text_short', uiType: 'text', icon: 'local-shipping', required: false },
            { name: 'Certificazione', type: 'single_choice', uiType: 'picker', icon: 'verified', required: false, options: [{ id: 'saga', label: 'SAGA' }, { id: 'kopenhagen', label: 'Kopenhagen' }, { id: 'nafa', label: 'NAFA' }, { id: 'altro', label: 'Altro' }], dataset: ['SAGA', 'Kopenhagen', 'NAFA', 'Altro'] },
            { name: 'Condizione', type: 'single_choice', uiType: 'segmented', icon: 'star', required: false, options: [{ id: 'nuova', label: 'Nuova' }, { id: 'ottima', label: 'Ottima' }, { id: 'buona', label: 'Buona' }, { id: 'usata', label: 'Usata' }], dataset: ['Nuova', 'Ottima', 'Buona', 'Usata'] },
            { name: 'Data Acquisto', type: 'date', uiType: 'date', icon: 'event', required: false },
        ],
    },
    {
        id: 'gioielleria',
        name: 'Gioielleria & Oreficeria',
        emoji: '💎',
        description: 'Carati, metallo, pietre, certificati gemmologici',
        color: '#FFD700',
        fields: [
            { name: 'Carati', type: 'number', uiType: 'text', icon: 'diamond', unit: 'ct', required: false },
            { name: 'Metallo', type: 'single_choice', uiType: 'grid', icon: 'auto-awesome', required: false, options: [{ id: 'oro_giallo', label: 'Oro Giallo' }, { id: 'oro_bianco', label: 'Oro Bianco' }, { id: 'oro_rosa', label: 'Oro Rosa' }, { id: 'argento', label: 'Argento' }, { id: 'platino', label: 'Platino' }], dataset: ['Oro Giallo', 'Oro Bianco', 'Oro Rosa', 'Argento', 'Platino'] },
            { name: 'Pietra Principale', type: 'single_choice', uiType: 'picker', icon: 'lens', required: false, options: [{ id: 'diamante', label: 'Diamante' }, { id: 'rubino', label: 'Rubino' }, { id: 'smeraldo', label: 'Smeraldo' }, { id: 'zaffiro', label: 'Zaffiro' }, { id: 'nessuna', label: 'Nessuna' }], dataset: ['Diamante', 'Rubino', 'Smeraldo', 'Zaffiro', 'Nessuna'] },
            { name: 'Certificato Gemma', type: 'single_choice', uiType: 'picker', icon: 'verified', required: false, options: [{ id: 'gia', label: 'GIA' }, { id: 'igi', label: 'IGI' }, { id: 'hrd', label: 'HRD' }, { id: 'nessuno', label: 'Nessuno' }], dataset: ['GIA', 'IGI', 'HRD', 'Nessuno'] },
            { name: 'Peso Oro', type: 'number', uiType: 'text', icon: 'fitness-center', unit: 'g', required: false },
            { name: 'Misura Anello', type: 'number', uiType: 'text', icon: 'radio-button-unchecked', unit: '', required: false },
            { name: 'Incisione', type: 'text_short', uiType: 'text', icon: 'edit', required: false },
        ],
    },
    {
        id: 'abbigliamento',
        name: 'Abbigliamento & Moda',
        emoji: '👗',
        description: 'Taglia, colore, tessuto, stagione, brand, linea',
        color: '#FF69B4',
        fields: [
            { name: 'Taglia', type: 'single_choice', uiType: 'segmented', icon: 'straighten', required: true, options: [{ id: 'xs', label: 'XS' }, { id: 's', label: 'S' }, { id: 'm', label: 'M' }, { id: 'l', label: 'L' }, { id: 'xl', label: 'XL' }, { id: 'xxl', label: 'XXL' }], dataset: ['XS', 'S', 'M', 'L', 'XL', 'XXL'] },
            { name: 'Colore', type: 'single_choice', uiType: 'grid', icon: 'palette', required: false, options: [{ id: 'nero', label: 'Nero' }, { id: 'bianco', label: 'Bianco' }, { id: 'blu', label: 'Blu' }, { id: 'rosso', label: 'Rosso' }, { id: 'verde', label: 'Verde' }, { id: 'grigio', label: 'Grigio' }], dataset: ['Nero', 'Bianco', 'Blu', 'Rosso', 'Verde', 'Grigio'] },
            { name: 'Tessuto', type: 'single_choice', uiType: 'picker', icon: 'texture', required: false, options: [{ id: 'cotone', label: 'Cotone' }, { id: 'lana', label: 'Lana' }, { id: 'seta', label: 'Seta' }, { id: 'lino', label: 'Lino' }, { id: 'sintetico', label: 'Sintetico' }, { id: 'misto', label: 'Misto' }], dataset: ['Cotone', 'Lana', 'Seta', 'Lino', 'Sintetico', 'Misto'] },
            { name: 'Brand', type: 'text_short', uiType: 'text', icon: 'sell', required: false },
            { name: 'Linea', type: 'text_short', uiType: 'text', icon: 'category', required: false },
            { name: 'Stagione', type: 'single_choice', uiType: 'segmented', icon: 'wb-sunny', required: false, options: [{ id: 'ai', label: 'A/I' }, { id: 'pe', label: 'P/E' }, { id: 'resort', label: 'Resort' }, { id: 'cruise', label: 'Cruise' }], dataset: ['A/I', 'P/E', 'Resort', 'Cruise'] },
        ],
    },
    {
        id: 'calzature',
        name: 'Calzature & Scarpe',
        emoji: '👟',
        description: 'Taglia EU/US, modello, colore, materiale',
        color: '#8B0000',
        fields: [
            { name: 'Taglia EU', type: 'number', uiType: 'text', icon: 'straighten', unit: '', required: true },
            { name: 'Taglia US', type: 'number', uiType: 'text', icon: 'straighten', unit: '', required: false },
            { name: 'Modello', type: 'text_short', uiType: 'text', icon: 'style', required: false },
            { name: 'Colore', type: 'single_choice', uiType: 'grid', icon: 'palette', required: false, options: [{ id: 'nero', label: 'Nero' }, { id: 'marrone', label: 'Marrone' }, { id: 'bianco', label: 'Bianco' }, { id: 'blu', label: 'Blu' }, { id: 'rosso', label: 'Rosso' }], dataset: ['Nero', 'Marrone', 'Bianco', 'Blu', 'Rosso'] },
            { name: 'Materiale', type: 'single_choice', uiType: 'picker', icon: 'layers', required: false, options: [{ id: 'pelle', label: 'Pelle' }, { id: 'camoscio', label: 'Camoscio' }, { id: 'tessuto', label: 'Tessuto' }, { id: 'gomma', label: 'Gomma' }, { id: 'sintetico', label: 'Sintetico' }], dataset: ['Pelle', 'Camoscio', 'Tessuto', 'Gomma', 'Sintetico'] },
            { name: 'Genere', type: 'single_choice', uiType: 'segmented', icon: 'wc', required: false, options: [{ id: 'uomo', label: 'Uomo' }, { id: 'donna', label: 'Donna' }, { id: 'unisex', label: 'Unisex' }], dataset: ['Uomo', 'Donna', 'Unisex'] },
        ],
    },
    {
        id: 'elettronica',
        name: 'Elettronica & Tech',
        emoji: '📱',
        description: 'Marca, modello, IMEI/seriale, garanzia, condizione',
        color: '#1E90FF',
        fields: [
            { name: 'Marca', type: 'text_short', uiType: 'text', icon: 'devices', required: true },
            { name: 'Modello', type: 'text_short', uiType: 'text', icon: 'smartphone', required: true },
            { name: 'IMEI / Seriale', type: 'text_short', uiType: 'text', icon: 'fingerprint', required: false },
            { name: 'Garanzia Fino A', type: 'date', uiType: 'date', icon: 'security', required: false },
            { name: 'Condizione', type: 'single_choice', uiType: 'segmented', icon: 'star', required: true, options: [{ id: 'nuovo', label: 'Nuovo' }, { id: 'come_nuovo', label: 'Come Nuovo' }, { id: 'buono', label: 'Buono' }, { id: 'discreto', label: 'Discreto' }], dataset: ['Nuovo', 'Come Nuovo', 'Buono', 'Discreto'] },
            { name: 'Memoria', type: 'single_choice', uiType: 'picker', icon: 'sd-storage', required: false, options: [{ id: '64', label: '64 GB' }, { id: '128', label: '128 GB' }, { id: '256', label: '256 GB' }, { id: '512', label: '512 GB' }, { id: '1024', label: '1 TB' }], dataset: ['64 GB', '128 GB', '256 GB', '512 GB', '1 TB'] },
            { name: 'Accessori Inclusi', type: 'multi_choice', uiType: 'grid', icon: 'cable', required: false, options: [{ id: 'caricatore', label: 'Caricatore' }, { id: 'cavo', label: 'Cavo' }, { id: 'custodia', label: 'Custodia' }, { id: 'auricolari', label: 'Auricolari' }, { id: 'scatola', label: 'Scatola' }], dataset: ['Caricatore', 'Cavo', 'Custodia', 'Auricolari', 'Scatola'] },
        ],
    },
    {
        id: 'vini',
        name: 'Vini & Liquori',
        emoji: '🍷',
        description: 'Annata, cantina, regione, gradazione, abbinamento',
        color: '#722F37',
        fields: [
            { name: 'Annata', type: 'number', uiType: 'text', icon: 'date-range', unit: '', required: false },
            { name: 'Cantina', type: 'text_short', uiType: 'text', icon: 'store', required: false },
            { name: 'Regione', type: 'text_short', uiType: 'text', icon: 'place', required: false },
            { name: 'Tipologia', type: 'single_choice', uiType: 'segmented', icon: 'local-bar', required: false, options: [{ id: 'rosso', label: 'Rosso' }, { id: 'bianco', label: 'Bianco' }, { id: 'rose', label: 'Rosé' }, { id: 'bollicine', label: 'Bollicine' }, { id: 'liquore', label: 'Liquore' }], dataset: ['Rosso', 'Bianco', 'Rosé', 'Bollicine', 'Liquore'] },
            { name: 'Gradazione', type: 'number', uiType: 'text', icon: 'speed', unit: '% vol', required: false },
            { name: 'Punteggio', type: 'number', uiType: 'stepper', icon: 'stars', unit: '/100', required: false, dataset: { min: 0, max: 100, step: 1 } },
            { name: 'Abbinamento', type: 'text_long', uiType: 'text', icon: 'restaurant', required: false },
        ],
    },
    {
        id: 'mobili',
        name: 'Mobili & Arredamento',
        emoji: '🛋️',
        description: 'Materiale, dimensioni, stanza, stile, finitura',
        color: '#8B6914',
        fields: [
            { name: 'Materiale', type: 'single_choice', uiType: 'picker', icon: 'layers', required: false, options: [{ id: 'legno', label: 'Legno Massello' }, { id: 'mdf', label: 'MDF' }, { id: 'metallo', label: 'Metallo' }, { id: 'vetro', label: 'Vetro' }, { id: 'tessuto', label: 'Tessuto' }, { id: 'pelle', label: 'Pelle' }], dataset: ['Legno Massello', 'MDF', 'Metallo', 'Vetro', 'Tessuto', 'Pelle'] },
            { name: 'Altezza', type: 'number', uiType: 'text', icon: 'height', unit: 'cm', required: false },
            { name: 'Profondità', type: 'number', uiType: 'text', icon: 'straighten', unit: 'cm', required: false },
            { name: 'Stanza', type: 'single_choice', uiType: 'grid', icon: 'meeting-room', required: false, options: [{ id: 'soggiorno', label: 'Soggiorno' }, { id: 'camera', label: 'Camera' }, { id: 'cucina', label: 'Cucina' }, { id: 'bagno', label: 'Bagno' }, { id: 'ufficio', label: 'Ufficio' }, { id: 'esterno', label: 'Esterno' }], dataset: ['Soggiorno', 'Camera', 'Cucina', 'Bagno', 'Ufficio', 'Esterno'] },
            { name: 'Stile', type: 'single_choice', uiType: 'picker', icon: 'style', required: false, options: [{ id: 'moderno', label: 'Moderno' }, { id: 'classico', label: 'Classico' }, { id: 'industriale', label: 'Industriale' }, { id: 'scandinavo', label: 'Scandinavo' }, { id: 'rustico', label: 'Rustico' }], dataset: ['Moderno', 'Classico', 'Industriale', 'Scandinavo', 'Rustico'] },
            { name: 'Finitura', type: 'text_short', uiType: 'text', icon: 'format-paint', required: false },
        ],
    },
    {
        id: 'auto',
        name: 'Auto & Veicoli',
        emoji: '🚗',
        description: 'Marca, modello, anno, km, telaio, cambio',
        color: '#2F4F4F',
        fields: [
            { name: 'Marca Veicolo', type: 'text_short', uiType: 'text', icon: 'directions-car', required: true },
            { name: 'Modello Veicolo', type: 'text_short', uiType: 'text', icon: 'drive-eta', required: true },
            { name: 'Anno', type: 'number', uiType: 'text', icon: 'date-range', unit: '', required: false },
            { name: 'Chilometraggio', type: 'number', uiType: 'text', icon: 'speed', unit: 'km', required: false },
            { name: 'N° Telaio', type: 'text_short', uiType: 'text', icon: 'fingerprint', required: false },
            { name: 'Cambio', type: 'single_choice', uiType: 'segmented', icon: 'settings', required: false, options: [{ id: 'manuale', label: 'Manuale' }, { id: 'automatico', label: 'Automatico' }], dataset: ['Manuale', 'Automatico'] },
            { name: 'Carburante', type: 'single_choice', uiType: 'picker', icon: 'local-gas-station', required: false, options: [{ id: 'benzina', label: 'Benzina' }, { id: 'diesel', label: 'Diesel' }, { id: 'gpl', label: 'GPL' }, { id: 'elettrico', label: 'Elettrico' }, { id: 'ibrido', label: 'Ibrido' }], dataset: ['Benzina', 'Diesel', 'GPL', 'Elettrico', 'Ibrido'] },
            { name: 'Scadenza Revisione', type: 'date', uiType: 'date', icon: 'event', required: false },
        ],
    },
    {
        id: 'orologi',
        name: 'Orologi & Luxury',
        emoji: '⌚',
        description: 'Marca, movimento, cassa, cinturino, referenza',
        color: '#C0C0C0',
        fields: [
            { name: 'Marca', type: 'text_short', uiType: 'text', icon: 'watch', required: true },
            { name: 'Referenza', type: 'text_short', uiType: 'text', icon: 'tag', required: false },
            { name: 'Movimento', type: 'single_choice', uiType: 'segmented', icon: 'settings', required: false, options: [{ id: 'automatico', label: 'Automatico' }, { id: 'quarzo', label: 'Quarzo' }, { id: 'manuale', label: 'Manuale' }], dataset: ['Automatico', 'Quarzo', 'Manuale'] },
            { name: 'Diametro Cassa', type: 'number', uiType: 'text', icon: 'radio-button-unchecked', unit: 'mm', required: false },
            { name: 'Materiale Cassa', type: 'single_choice', uiType: 'picker', icon: 'layers', required: false, options: [{ id: 'acciaio', label: 'Acciaio' }, { id: 'oro', label: 'Oro' }, { id: 'titanio', label: 'Titanio' }, { id: 'ceramica', label: 'Ceramica' }, { id: 'carbonio', label: 'Carbonio' }], dataset: ['Acciaio', 'Oro', 'Titanio', 'Ceramica', 'Carbonio'] },
            { name: 'Cinturino', type: 'single_choice', uiType: 'grid', icon: 'watch-later', required: false, options: [{ id: 'bracciale', label: 'Bracciale' }, { id: 'pelle', label: 'Pelle' }, { id: 'gomma', label: 'Gomma' }, { id: 'nato', label: 'NATO' }], dataset: ['Bracciale', 'Pelle', 'Gomma', 'NATO'] },
            { name: 'Documenti', type: 'multi_choice', uiType: 'grid', icon: 'description', required: false, options: [{ id: 'scatola', label: 'Scatola' }, { id: 'garanzia', label: 'Garanzia' }, { id: 'certificato', label: 'Certificato' }], dataset: ['Scatola', 'Garanzia', 'Certificato'] },
        ],
    },
    {
        id: 'cosmetici',
        name: 'Cosmetici & Bellezza',
        emoji: '💄',
        description: 'Tipo pelle, ingredienti, scadenza, linea, formato',
        color: '#FF1493',
        fields: [
            { name: 'Tipo Pelle', type: 'single_choice', uiType: 'grid', icon: 'face', required: false, options: [{ id: 'secca', label: 'Secca' }, { id: 'grassa', label: 'Grassa' }, { id: 'mista', label: 'Mista' }, { id: 'sensibile', label: 'Sensibile' }, { id: 'normale', label: 'Normale' }], dataset: ['Secca', 'Grassa', 'Mista', 'Sensibile', 'Normale'] },
            { name: 'Ingredienti Chiave', type: 'text_long', uiType: 'text', icon: 'science', required: false },
            { name: 'Scadenza', type: 'date', uiType: 'date', icon: 'event', required: false },
            { name: 'Linea', type: 'text_short', uiType: 'text', icon: 'category', required: false },
            { name: 'Formato', type: 'single_choice', uiType: 'picker', icon: 'straighten', required: false, options: [{ id: 'crema', label: 'Crema' }, { id: 'siero', label: 'Siero' }, { id: 'olio', label: 'Olio' }, { id: 'spray', label: 'Spray' }, { id: 'polvere', label: 'Polvere' }], dataset: ['Crema', 'Siero', 'Olio', 'Spray', 'Polvere'] },
            { name: 'Volume/Peso', type: 'number', uiType: 'text', icon: 'straighten', unit: 'ml', required: false },
        ],
    },
    {
        id: 'alimentari',
        name: 'Alimentari & Food',
        emoji: '🍝',
        description: 'Scadenza, lotto, allergeni, provenienza, bio',
        color: '#228B22',
        fields: [
            { name: 'Scadenza', type: 'date', uiType: 'date', icon: 'event', required: true },
            { name: 'Lotto', type: 'text_short', uiType: 'text', icon: 'tag', required: false },
            { name: 'Allergeni', type: 'multi_choice', uiType: 'grid', icon: 'warning', required: false, options: [{ id: 'glutine', label: 'Glutine' }, { id: 'lattosio', label: 'Lattosio' }, { id: 'uova', label: 'Uova' }, { id: 'frutta_secca', label: 'Frutta Secca' }, { id: 'soia', label: 'Soia' }, { id: 'pesce', label: 'Pesce' }], dataset: ['Glutine', 'Lattosio', 'Uova', 'Frutta Secca', 'Soia', 'Pesce'] },
            { name: 'Provenienza', type: 'text_short', uiType: 'text', icon: 'public', required: false },
            { name: 'Biologico', type: 'single_choice', uiType: 'segmented', icon: 'eco', required: false, options: [{ id: 'si', label: 'Sì' }, { id: 'no', label: 'No' }], dataset: ['Sì', 'No'] },
            { name: 'Temperatura Conservazione', type: 'single_choice', uiType: 'segmented', icon: 'thermostat', required: false, options: [{ id: 'ambiente', label: 'Ambiente' }, { id: 'fresco', label: 'Fresco' }, { id: 'surgelato', label: 'Surgelato' }], dataset: ['Ambiente', 'Fresco', 'Surgelato'] },
        ],
    },
    {
        id: 'farmacia',
        name: 'Farmacia & Parafarmacia',
        emoji: '💊',
        description: 'Principio attivo, scadenza, lotto, AIC, dosaggio',
        color: '#006400',
        fields: [
            { name: 'Principio Attivo', type: 'text_short', uiType: 'text', icon: 'science', required: true },
            { name: 'Scadenza', type: 'date', uiType: 'date', icon: 'event', required: true },
            { name: 'N° Lotto', type: 'text_short', uiType: 'text', icon: 'tag', required: false },
            { name: 'Codice AIC', type: 'text_short', uiType: 'text', icon: 'qr-code', required: false },
            { name: 'Dosaggio', type: 'text_short', uiType: 'text', icon: 'medication', unit: 'mg', required: false },
            { name: 'Forma', type: 'single_choice', uiType: 'picker', icon: 'medication', required: false, options: [{ id: 'compressa', label: 'Compressa' }, { id: 'capsula', label: 'Capsula' }, { id: 'sciroppo', label: 'Sciroppo' }, { id: 'crema', label: 'Crema' }, { id: 'iniezione', label: 'Iniezione' }], dataset: ['Compressa', 'Capsula', 'Sciroppo', 'Crema', 'Iniezione'] },
            { name: 'Ricetta', type: 'single_choice', uiType: 'segmented', icon: 'receipt', required: false, options: [{ id: 'otc', label: 'OTC' }, { id: 'sop', label: 'SOP' }, { id: 'ricetta', label: 'Con Ricetta' }], dataset: ['OTC', 'SOP', 'Con Ricetta'] },
        ],
    },
    {
        id: 'arte',
        name: 'Arte & Antiquariato',
        emoji: '🎨',
        description: 'Artista, epoca, tecnica, certificato, provenienza',
        color: '#800080',
        fields: [
            { name: 'Artista', type: 'text_short', uiType: 'text', icon: 'brush', required: false },
            { name: 'Epoca', type: 'text_short', uiType: 'text', icon: 'history', required: false },
            { name: 'Tecnica', type: 'single_choice', uiType: 'picker', icon: 'create', required: false, options: [{ id: 'olio', label: 'Olio su tela' }, { id: 'acquerello', label: 'Acquerello' }, { id: 'acrilico', label: 'Acrilico' }, { id: 'scultura', label: 'Scultura' }, { id: 'stampa', label: 'Stampa' }, { id: 'mista', label: 'Tecnica Mista' }], dataset: ['Olio su tela', 'Acquerello', 'Acrilico', 'Scultura', 'Stampa', 'Tecnica Mista'] },
            { name: 'Certificato Autenticità', type: 'single_choice', uiType: 'segmented', icon: 'verified', required: false, options: [{ id: 'si', label: 'Sì' }, { id: 'no', label: 'No' }], dataset: ['Sì', 'No'] },
            { name: 'Provenienza', type: 'text_long', uiType: 'text', icon: 'place', required: false },
            { name: 'Numero Edizione', type: 'text_short', uiType: 'text', icon: 'format-list-numbered', required: false },
        ],
    },
    {
        id: 'tessuti',
        name: 'Tessuti & Stoffe',
        emoji: '🧵',
        description: 'Composizione, peso g/m², altezza, colore, lavaggio',
        color: '#4169E1',
        fields: [
            { name: 'Composizione', type: 'text_short', uiType: 'text', icon: 'science', required: true },
            { name: 'Peso Tessuto', type: 'number', uiType: 'text', icon: 'fitness-center', unit: 'g/m²', required: false },
            { name: 'Altezza Tessuto', type: 'number', uiType: 'text', icon: 'height', unit: 'cm', required: false },
            { name: 'Colore', type: 'single_choice', uiType: 'grid', icon: 'palette', required: false, options: [{ id: 'nero', label: 'Nero' }, { id: 'bianco', label: 'Bianco' }, { id: 'blu', label: 'Blu' }, { id: 'rosso', label: 'Rosso' }, { id: 'fantasia', label: 'Fantasia' }, { id: 'multicolor', label: 'Multicolor' }], dataset: ['Nero', 'Bianco', 'Blu', 'Rosso', 'Fantasia', 'Multicolor'] },
            { name: 'Manutenzione', type: 'multi_choice', uiType: 'grid', icon: 'local-laundry-service', required: false, options: [{ id: 'lavabile', label: 'Lavabile' }, { id: 'secco', label: 'Solo a Secco' }, { id: 'ferro', label: 'Stirabile' }, { id: 'no_candeggina', label: 'No Candeggina' }], dataset: ['Lavabile', 'Solo a Secco', 'Stirabile', 'No Candeggina'] },
            { name: 'Metratura Disponibile', type: 'number', uiType: 'text', icon: 'straighten', unit: 'm', required: false },
        ],
    },
    {
        id: 'ottica',
        name: 'Ottica & Occhialeria',
        emoji: '👓',
        description: 'Marca, modello, lenti, montatura, diottrie',
        color: '#4682B4',
        fields: [
            { name: 'Marca', type: 'text_short', uiType: 'text', icon: 'visibility', required: true },
            { name: 'Modello', type: 'text_short', uiType: 'text', icon: 'style', required: false },
            { name: 'Tipo', type: 'single_choice', uiType: 'segmented', icon: 'visibility', required: false, options: [{ id: 'vista', label: 'Da Vista' }, { id: 'sole', label: 'Da Sole' }, { id: 'sport', label: 'Sportivi' }], dataset: ['Da Vista', 'Da Sole', 'Sportivi'] },
            { name: 'Materiale Montatura', type: 'single_choice', uiType: 'picker', icon: 'layers', required: false, options: [{ id: 'metallo', label: 'Metallo' }, { id: 'acetato', label: 'Acetato' }, { id: 'titanio', label: 'Titanio' }, { id: 'plastica', label: 'Plastica' }], dataset: ['Metallo', 'Acetato', 'Titanio', 'Plastica'] },
            { name: 'Colore Montatura', type: 'single_choice', uiType: 'grid', icon: 'palette', required: false, options: [{ id: 'nero', label: 'Nero' }, { id: 'oro', label: 'Oro' }, { id: 'argento', label: 'Argento' }, { id: 'tartaruga', label: 'Tartaruga' }, { id: 'trasparente', label: 'Trasparente' }], dataset: ['Nero', 'Oro', 'Argento', 'Tartaruga', 'Trasparente'] },
            { name: 'Lenti', type: 'single_choice', uiType: 'picker', icon: 'lens', required: false, options: [{ id: 'polarizzate', label: 'Polarizzate' }, { id: 'fotocromatiche', label: 'Fotocromatiche' }, { id: 'progressive', label: 'Progressive' }, { id: 'standard', label: 'Standard' }], dataset: ['Polarizzate', 'Fotocromatiche', 'Progressive', 'Standard'] },
        ],
    },
];

// User custom templates storage key
export const USER_TEMPLATES_KEY = 'furinventory_user_templates';
